### ISSUE TITLE
List files where a hash is present but the file is not accessible

### ISSUE THREAD

**Issue by ralle12345** [trapexit/scorch#15]
How about a function for scorch where the hash database is checked for files that are missing - i.e. a hash is in the databasem but the corresponding file is not found in the expected path.

The use case for such a function could be if you decide to live without a RAID but want to know which files are gone for good _after_ a disk fails faster than you can move the files off the platters.

**Comment by trapexit** [comment]
It already has that ability. `list-missing`

**Comment by ralle12345** [comment]
But the feature is not mentioned in the project's description. You may want 
to add it to the readme.MD.

Am 1. Juni 2018 16:06:08 schrieb trapexit <notifications@github.com>:

**Comment by trapexit** [comment]
True. I just forgot whenever I originally created it. It's in the usage though.
