### ISSUE TITLE
Support for progressive write to disk

### ISSUE THREAD

**Issue by aw** [trapexit/scorch#33]
Hi,

When running a checksum that takes a few hours (ex: a dir with many large files), if the machine crashes or `scorch` exits before it completes, **all results are lost**.

It would be nice if `scorch` could periodically write-to-disk_ to prevent losing many hours of work. My suggestion would be to write every five minutes or every _N_ entries (perhaps configurable?). Thanks!

**Comment by trapexit** [comment]
>exits before it completes

What do you mean by this? If it is interrupted by a SIGINT or there is some general internal errors it will write to disk whatever it processed. Start it up and then hit CTRL-C and you'll see.

It does skip writing for certain errors which I could change but it'd be good to understand what exactly you're talking about.

>periodic writes

I've been considering rewriting the database code anyway and that would address this all this. I'll probably look into doing that first.

**Comment by aw** [comment]
Oh you're right! It does write to disk on SIGINT! Sorry about that.

I think the use-case for periodic writes still exists though, for cases where the server crashes unexpectedly.

**Comment by trapexit** [comment]
Sure. I have to consider the options. If I move to using SQLite then probably I'd just have everything happen as soon as possible since it's designed for that. As of now it atomically writes a new file once a file or directory argument is done processing because it's stored in a compressed CSV and with large sets of data it'd be too much to write a new file after each line.

**Comment by aw** [comment]
SQLite would be a very welcome addition ;)

In fact, I didn't realize `scorch` can process individual files, not just whole directories.. in that case, perhaps I can just use a simple shell `for` loop:

```
cd /path/to/files
for i in $(ls); do scorch -d test.db -v append "$i"; done
```

This works perfectly when all files are in the same directory, but I'm sure a variation with `find` would work just as well. Perhaps we can close this issue. Thanks!

**Comment by aw** [comment]
RE: SQLite, I just published a small script which handles converting a `scorch` DB to SQLite. I needed this to add a `tags` column to the DB with additional metadata for each scanned file:

https://github.com/aw/scorch-to-sqlite

**Comment by trapexit** [comment]
Could also do something with xargs. scorch takes multiple args. Files or directories.

find -type f -print0 | xargs -0 scorch ...

What kind of metadata? I originally didn't use sqlite because I didn't realize that for Python3 it was part of the base platform. I try to limit my dependencies and on Python2 it was a 3rd party dependency. If I'm going to use it though I will be adding more metadata like some timestamps for when it was added and when last checked. Then you can do something more like snapraid scrub.

**Comment by aw** [comment]
That sounds great. I'm planning for metadata such as tags, which would be added manually, similar to tags added to S3 Objects.

**Comment by trapexit** [comment]
So... I'm deep into a change to sqlite and I'm second guessing the strategy. Mostly it comes to the verbosity of using sqlite over coding it yourself and moreso the fact that I apply similar filters and sorting to both data coming from disk and from the database. To do it "properly" means having 2 sets of filters and sorting.

I'll keep tinkering to see how much of a pain it is but it's probably easier to add what I have in mind to what exists.

**Comment by aw** [comment]
Thanks for the heads-up. It's no rush, please take your time.

`Scorch` has been awesome for me so far. I'll keep updated with this project and will be glad to test the new feature(s) you decide to implement.

**Comment by trapexit** [comment]
https://github.com/trapexit/scorch/tree/updates

If you're willing... here's a first draft.

**Comment by aw** [comment]
Hey it looks great!

I watched the file before running with the `append` command:

```
inotifywait -m scorch.db
```

and I could see the `OPEN`, `MODIFY`, `WRITE`... for each file being hashed. That's reassuring.

I noticed you added a `list-changed` and `list-failed` commands as well thanks to the new metadata, those will be useful too. Thanks!

**Comment by trapexit** [comment]
It works by appending new records each time it has a modification. Since it's a csv file and how it loads them top to bottom it in effect overwrites it. But that is inefficient with regards to storage. One because it has multiple entries but also because the compression is poor saving one line compressed at a time. So at the end it will read the db and rewrite it if it sees the mtime has changed. Not ideal but it works. sqlite would be better in theory but I found it a major pain to work with in this case given the need to sort and filter inside the DB and out.

I'm going to add a time based stop like the -m and -M arguments and then maybe cut a release. Then you can easily do a time limited check of data sorted by the last time it was checked and can use list-failed or list-changed to see what it found (for those without email setup for cron or whatnot.)

**Comment by trapexit** [comment]
If you have the time please try to break it. I changed a lot of stuff. Might need to invest in some integration tests.

**Comment by aw** [comment]
OK I did some testing, and I noticed a something:

* when running `check+update`, if the data hasn't changed, the `checked` and `state` columns in the DB don't change..

Your code should be setting the `state` to `C` according to:

https://github.com/trapexit/scorch/compare/updates#diff-bf4d9300fc35431eb3ac982c17b6dd0dR628 

but I'm not a Python expert, so I can't quickly tell what's going on.

**Comment by aw** [comment]
Sorry I deleted my previous comment because I was checking the backup DB file for changes haha oops.

OK I did some testing, and I noticed something:

* when running `check`, if the data hasn't changed, the `state` column in the DB is set to `O` instead of `C`, which according to the code should only be set to `O` if there's an actual update (but mtime & hash haven't changed either).

While writing this, I think I found the problem here:

https://github.com/trapexit/scorch/compare/updates#diff-bf4d9300fc35431eb3ac982c17b6dd0dR662

Should this be `C` instead of `O` ? unless there's a specific reason why _verbose_ mode would set the file's state to `O` instead of `C` when no changes were made?

**Comment by trapexit** [comment]
`O` means OK. `C` means changed. `U` means unknown. `F` means failed.

Why would set it to 'changed' when that section means that nothing changed and checked out OK?

**Comment by aw** [comment]
Ohhh my bad, for some reason I thought `C` meant `changed` 😆 

In that case, everything seems fine according to my tests, but I may have missed something as well.

**Comment by trapexit** [comment]
Added and pushed to the same branch the timeout feature. `-T 1h` will cause it to exit after 1 hour.

**Comment by aw** [comment]
I haven't tried that feature yet. Will try it this week.

I did notice older versions of the `scorch` client don't work with the newer database format. I get the error _"unknown data layout in scorch database"_ unless I checkout the `updates` branch.

This is a problem (i.e: on read-only media such as DVDs and Blu-Rays), since it would be impossible to `check` if that data is corrupt unless using an older version of `scorch`...

**Comment by trapexit** [comment]
>I did notice older versions of the scorch client don't work with the newer database format. I get the error "unknown data layout in scorch database" unless I checkout the updates branch.

There isn't a way to go back in time and change the code so... it what it is.

>This is a problem (i.e: on read-only media such as DVDs and Blu-Rays), since it would be impossible to check if that data is corrupt unless using an older version of scorch...

? The current version, within reason, converts the older versions. It's backwards compatible. Old versions are not forwards compatible. Those are different situations.

**Comment by aw** [comment]
Right, but if the DB created from commit 1bf40306fe23ac1546810832e017dca9fab3c385 is on a read-only media such as a DVD, and I use the latest `scorch` from commit 1aab821d612964d5a7d429889537276c01272e86 then it can't run a `check` on that database anymore (see error posted above). I guess I could just _copy_ the database to disk and perform the DB conversion, or also save that version of `scorch` alongside the DB it created..

**Comment by trapexit** [comment]
Why is that? A read only db reads and is converted at runtime just fine. I just tried it. It just won't be able to update the database to include the new information but that should be obvious. 

I don't really understand. The DB is a living thing. It's intended to be read-write. Not read-only. If you want to be able to have things like state and last checked timestamps there is no way to make it not read-write. The current code spits out an error when it can't update the db. What would you prefer? No error? Ignore updates if the file is read only? No such feature?

**Comment by aw** [comment]
Perhaps I'm taking the wrong approach at this, I'm still testing the functionality of this tool and trying to see how to make it work with my workflow, but it seems my approach might not be ideal. Anyways thanks for all your help.

**Comment by trapexit** [comment]
Checking from read only DBs is fine, and works, but I need to understand what your concern is. You implied strongly above that it doesn't work but it does as far as I can tell... just spits out errors when trying to write to disk the updated record indicating when it was checked and the result of that check. What do you want / expect? No error? A warning it's read only at startup?

**Comment by aw** [comment]
Sorry, I think I made a mistake.

I just ran more tests and realized `scorch` isn't forward compatible with newer database formats, but it **is** backward compatible with older DB formats. That makes sense.

My "read-only DB" comment was incorrect. Sorry about that.

**Comment by trapexit** [comment]
np. I'm tweaking the behavior to ignore the error generally and make it report to stderr a warning when reading that it's read only.

**Comment by aw** [comment]
@trapexit just a small update, I found some **corrupt** files on a backup since I started hashing with `scorch` (caused by UDMA CRC errors), and the `list-changed` and `list-failed` commands have been VERY helpful to quickly see which files should be re-backed up.

Previously I was saving the `check` results to a file and then grepping/parsing that. These command options eliminate the need for that. Thanks!

**Comment by aw** [comment]
I guess that means I _should not_ put the DB on read-only media 😉

**Comment by trapexit** [comment]
It's fine if you do. It **will** work. Just won't get the benefits of that feature. I suppose I could have a read-db and write-db but that seems overly complex. In the end it'd be the same as copying the db somewhere read-write.

**Comment by aw** [comment]
Yes exactly, for files which need to be checked often, I think as you mentioned previously:

> The DB is a living thing

It's better if I can write to it because it'll store the status during the checks, and makes it much easier to update files and update the DB. Thanks for your support.

**Comment by aw** [comment]
Hi @trapexit, I noticed you did a few "force pushes" to the `updates` branch.

I'm using that branch now because my database was updated to that format.. do you think you can _avoid_ doing rebases/force pushes to that branch? Or make some tags or something instead?

```
commit 31ec2ce8eda94e9514f95745e6b169af19896eaa (HEAD -> updates, origin/updates)
Author: Antonio SJ Musumeci <trapexit@spawn.link>
Date:   Fri May 1 13:20:39 2020 -0400

    misc updates
    
    * add last checked timestamp and known state
    * append updates and adds to db realtime
    * add 'checked' sort algo
    * rename 'reverse' to 'desc' in sorts
    * tweak error handling
    * add 'list-failed' and 'list-changed' instructions
    * add time based expiring (like count and size)
```

```
commit bdd60df06a7855594effbbeb8ed4cb5d63013621 (HEAD -> updates, origin/updates)
Author: Antonio SJ Musumeci <trapexit@spawn.link>
Date:   Fri May 1 13:20:39 2020 -0400

    misc updates
    
    * add last checked timestamp and known state
    * append updates and adds to db realtime
    * add 'checked' sort algo
    * rename 'reverse' to 'desc' in sorts
    * tweak error handling
    * add 'list-failed' and 'list-changed' instructions
    * add time based expiring (like count and size)
```

**Comment by trapexit** [comment]
This is my work branch. I need to force push so I can merge it into master. 

What's the problem?

**Comment by aw** [comment]
Hmmm.. well the problem is _force pushing breaks things_, perhaps I can suggest a better approach:

1. continue making all your changes in the `updates` branch, as usual
2. don't rebase/force push
3. when you're _ready_ to merge to master: `git checkout master; git merge updates; git rebase -i; # interactive rebase?`

This way you can rebase only at the end of your work, and you'll still have a history of all changes made up until your rebase (in the `updates`) branch. When you're done you can just delete the `updates` branch if needed, the commits will still be there so it won't break for anyone.

I've been using that approach since the early days of git, and it's friendly and still allows you to have one nice big clean commit in the `master` branch (once you merge).

**Comment by trapexit** [comment]
Breaks what things? Are you doing development off this branch?

I know how to use git. I mixed a bunch of random stuff into this branch and it's too late to pick out individual changes. The history is already lost. Hence the big commit.

**Comment by trapexit** [comment]
This was intended to be an experiment for you to play with. Not anything final. If you want to do you own development, the only reason force pushes would break anything as you can pick it up by a fetch and reset, then branch from master. There is no reason should break anything for you.

**Comment by aw** [comment]
I'm not doing development, but I was planning on using _scorch_ on more than one system and then I realized the same branch has different commit history. No worries, I'll wait until you merge your changes to `master`. Thanks.
