### ISSUE TITLE
Scorch exits early on Raspberry Pi3 due to use of sys.maxsize

### ISSUE THREAD

**Issue by azurefreecovid** [trapexit/scorch#36]
Hi @trapexit,

I've been using Scorch on a RaspberryPi 3 today and noticed that it exists after a couple of hours (exit code 0) without having processed all the files.

This is caused by the use of ``sys.maxsize`` for a number of the default parameter values in Scorch. On the RaspberryPi, due to its CPU architecture, Python3's ``sys.maxsize`` == 2147483647, which I believe is causing Scorch to exit.

I know that I can change these options on the command line, but I was also wondering if it might make sense to change the default values instead? Perhaps to ``2**64/2``?? Which is the default of ``sys.maxsize`` on most ``x64`` systems. 

Have a great weekend!

**Comment by trapexit** [comment]
I was under the impression it was a bigint value that was at least 64bit. Sure. I can change that to something explicit.

**Comment by azurefreecovid** [comment]
Hmm, it might be on other systems. This is what I get on my RaspPi - Buster:
```
pi@raspberrypi:~$ uname -a
Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
pi@raspberrypi:~$ python3 --version
Python 3.7.3
pi@raspberrypi:~$ python3 
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.maxsize
2147483647
>>> 
```

**Comment by trapexit** [comment]
It was probably the maxdata value being hit. Doubt you hit 2B files or seconds :)

I'll have a fix in a few.

**Comment by trapexit** [comment]
OK... change is in master.

**Comment by azurefreecovid** [comment]
Brilliant. Thanks!!
