### ISSUE TITLE
scorch data stored in xmp files instead of db

### ISSUE THREAD

**Issue by criadoperez** [trapexit/scorch#40]
Several free software photography tools like darktable store all the metadata, and the changes they make in the image in an xmp file with the same name. Original file is never touched.
Would it be possible to give scorch a feature where the  checksum information is stored in these same xmp files instead of the  database file?
The main benefits of this, is that other apps like darktable or digikam that will also be able to access and use the scorch information from the xmp file. Scorch could even be integrated and launched from these apps directly.
Most photographs don't store checksums of their photos, but just like everybody else , they suffer the consequences when it happens. This way, as soon as data corruption occurs it can be detected and the photographer can delete the corrupt file and restore a backup of just that file.

**Comment by trapexit** [comment]
Are you saying that darktable and digikam can read hashes from those files and will inform the user if they don't match? Even if they did why wouldn't they just write the hash if it wasn't there?

**Comment by criadoperez** [comment]
No. Currently they can't. But they easily could implement a feature or plugin that optionally did and informs the user if the hashes don't match.
The next step would be to create that feature or plugin in digikam/darktable. But instead of creating it again from scratch and doing it differently in every software application (like darktable or digikam), we might as well all use the same style and format, and all use a "standard" tool that already exists.

**Comment by trapexit** [comment]
I'm sorry but I'm not understanding. If they don't do it now and would need to add the feature to check the hash why wouldn't they also just add the creation of said hash? I don't understand what scorch has to do with this.

**Comment by criadoperez** [comment]
Let me try to explain myself a bit better.

What I'm proposing is being able to type something like this:

`scorch --xml myphoto.dng `

This command will search for the _myphoto.dng.xml_ file. If it doesn't exist, it will do nothing. If it does, it will append the hash information of _myphoto.dng_ in the _myphoto.dng.xml_ file, with all the relevant information in it. For example, the type of hash, timestamp of when the hash was first created, timestamp of when it was last checked, result of that last check and other relevant information.

You could also do it by folder with something like:
`scorch --xml myphotofolder`
In this case, it will search all the xml files in the folder and process them accordingly, like in the example above.

Once you have this command you can either run it manually or integrate in other applications. Darktable, digikam and other programs could call scorch and integrate it in their software. The user can optionally then activate/deactivate scorch or decide if a corruption check should run every time an image is loaded or not. 

Yes, you are right, darktable and digikam could create a hash themselves each in their own way without scorch.  But, a much better solution would be to have the hash information that's in the xml file, stored in a standardized format, so multiple applications can understand it and use it. I'm proposing here is using the scorch format for this and make it become the _standard_, instead of waiting for each application to design their own. Also, why re-write something that already works?

Just like multiple image applications use imagemagick, exiv2, lensfun or many others... re-using other applications that already do a great job is a much better alternative than re-creating and maintaining a new feature.

Also, what I'm proposing should be relatively easy and fast to implement right?

**Comment by trapexit** [comment]
I understand what you are proposing. What I am confused about is why.

>Also, why re-write something that already works?

Because scorch is not special with regard to hashing files. Lots and lots of software already do this. If there is a standard for storing metadata about images then it would seem natural for these programs to use said standards. Just add hashing to the list of things they already store. It's quite trivial.

No one in their right mind would use scorch to hash files from another program. Hashing files is trivial and nothing keeps them from doing it. The code is probably public domain and lots of software already do it.

>Also, what I'm proposing should be relatively easy and fast to implement right?

Yes, it's easy. It also doesn't make any sense to me. You should talk to darktable and digikam and suggest adding the storing of some hashes. The amount of work to have them use scorch would be more than just doing the hashing themselves.

**Comment by criadoperez** [comment]
Ok, understood. I'll try then to approach the problem another way.
Thanks anyway for your answers.
Have a great day!
